### ISSUE TITLE
Create/Destroy loop for SigOpt

### ISSUE THREAD

**Issue by nmashouf** [mp-interns/eratosthenes#16]
I'm almost done with the wrapper loop for SigOpt, but have run into a problem: each time we create a new experiment, the experiment ID changes so we have to ask for it in some way from the experiment object in order to delete that experiment. The problem is I'm not sure how we can access that using the API (I've been looking through their documentation)! I just emailed them but if anyone has any insight, let me know!

**Comment by dwinston** [comment]
According to the "create" documentation (
https://sigopt.com/docs/endpoints/experiments/create), you can save the
response and peek inside it for the experiment ID.

**Comment by nmashouf** [comment]
Oh okay, so for the example the experiment id is 1? Thank you! It looks like we can set the id ourselves then?

**Comment by dwinston** [comment]
Hmm, yeah, looks like you can. :)

**Comment by dwinston** [comment]
I would still confirm the id from the response, in case there is lag between you destroying an experiment and it actually being destroyed

**Comment by nmashouf** [comment]
Okay sounds good, thanks!
Another note: I'm trying to have A and B be categorical parameters, but it exceeds the "number of categorical values [our] plan allows"! I'll go back to the integer type for A and B.

**Comment by dwinston** [comment]
Interesting! Yes, pure categorical optimization seems hard. I found a study [1] where they essentially try to convert categorical variables to integer variables with "sorting" schemes.

[1] [Pure Categorical Optimization – a Global Descent Approach.pdf](https://github.com/mp-interns/eratosthenes/files/742/Pure.Categorical.Optimization.a.Global.Descent.Approach.pdf)

**Comment by nmashouf** [comment]
Update on loop: Good news is I got it to work! Yay! Bad news is our plan only takes 150 data points, INCLUDING historical data :( so once we transfer the historical data over and try the next data point, we hit our limit.

**Comment by dwinston** [comment]
Boo. I'll close this issue in that case. Thanks for trying. :)
