### ISSUE TITLE
List of our (~8k?) materials for which reasonable elastic constants can be computed

### ISSUE THREAD

**Issue by dwinston** [mp-interns/eratosthenes#5]
@chenweis can you help out here? Getting the materials for which data is available is trivial, but can you provide some code/guidance on how to get the full "potential" set of MP materials?

**Comment by chenweis** [comment]
The criteria I used for the current material list for elastic constant
calculations are:
- nelements <=3 (Most technologically relevant materials have <=3 main
  elements)
- nsites <= 12 (In conventional cell, mainly for computational cost
  consideration)
- e_above_hull < 0.1 eV
- has element ["C", "Mg", "Al", "Zn", "Ni", "Fe", "W", "Co", "Nb", "Hf",
  "Sc", "V", "Cu", "Zr", "Ti", "Pd", "Pt"]

**Comment by dwinston** [comment]
@chenweis, does the following fit the bill? I constructed it from your description using https://github.com/materialsproject/mapidoc.

```
elements = ["C", "Mg", "Al", "Zn", "Ni", "Fe", "W", "Co", "Nb",
            "Hf", "Sc", "V", "Cu", "Zr", "Ti", "Pd", "Pt"]
# `m` is a pymatgen.MPRester instance
m.query(criteria={"nelements": {"$lte": 3},
                  "nsites": {"$lte": 12},
                  "e_above_hull": {"$lte": 0.1},
                  "elements": {"$in": elements}},
        properties=["material_id"])
```

It returns ~6800 materials. Does the root "nsites" key for a material correspond to a conventional cell?

**Comment by chenweis** [comment]
The nsites key is for primitive cell, but I think you can use that number
instead.

Also, if you want to have more materials in the pool, "nelements<=4" can be
used.

**Comment by tschaume** [comment]
How severe would the consequences be on the computational time when opening up the `nsites <= 12` requirement? In case our algorithm works, we might be able to include materials with more sites since we're saving time by only calculating the promising ones.

**Comment by chenweis** [comment]
Large structures are very expensive for elastic constant calculations. DFT
approximately scales with the O(n^3), n=number of electrons. If you can
come up with a short list of large structures, it's still possible to
calculate them individually.

**Comment by dwinston** [comment]
I think we can call this closed. My `MPRester.query` example earlier in this thread should be sufficient.
