### ISSUE TITLE
Getting current MP elasticity data

### ISSUE THREAD

**Issue by dwinston** [mp-interns/eratosthenes#6]
@HGeerlings asked about simple programmatic access to MP's elastic constants data. While there are no specific methods in pymatgen's [MPRester](https://github.com/materialsproject/pymatgen/blob/6a3d8f589f5135210baa49ee01edba107db8de0a/pymatgen/matproj/rest.py) yet, you can use it's `query` method in consultation with our [API repository](https://github.com/materialsproject/mapidoc) to fish out what to do. All elasticity data for a material is stored under the ['elasticity' root level key](https://github.com/materialsproject/mapidoc/blob/60c85820ae4cb698f5895ed8a7d3a434fdcc3c28/materials/elasticity/README.md). For example,

```
from pymatgen import MPRester
# Assuming you've done `export MAPI_KEY="USER_API_KEY"` at the command line
# See materialsproject.org/dashboard to get your API key
m = MPRester()
data = m.query(criteria={"elasticity": {"$exists": True}},
                         properties=["formula", "elasticity.K_VRH"])
# print("{} results".format(len(data)))
# data[:5]
```

Will give you bulk moduli and reduced cell formulae (see materialsproject/mapidoc#7 for a list of "aliases") for all MP materials that have elasticity data (you'd get tens of thousands of `None`-valued results if you set `criteria={}` above).

Let me know if there are issues getting the above to run for you.

**Comment by HGeerlings** [comment]
Seems to work great. 

For reference, thought I would share a helpful <a href="https://github.com/materialsproject/mapidoc/blob/60c85820ae4cb698f5895ed8a7d3a434fdcc3c28/materials/elasticity/README.md">link</a> I found on the MP github (courtesy of Donny) that lists other elastic properties. 

Thanks!

**Comment by dwinston** [comment]
OK, looks like everyone's up and running with this!
