### ISSUE TITLE
Open source optimization engine

### ISSUE THREAD

**Issue by HGeerlings** [mp-interns/eratosthenes#7]
<a href="http://yelp.github.io/MOE/index.html">MOE</a> is an open source SigOpt-y type optimization software, <a href="https://github.com/Yelp/moe">repo</a>. Although we are focused on GAs, perhaps this may come in handy later on.

**Comment by dwinston** [comment]
Yeah, that looks great! I like that it can run as an isolated service. Because it is open-source, I would be happy with us trying this before trying SigOpt.

**Comment by tschaume** [comment]
:+1:

**Comment by HGeerlings** [comment]
Another interesting related software:

http://uspex.stonybrook.edu/uspex.html

**Comment by nmashouf** [comment]
Great video explanation/demo of MOE by a Yelp software engineer:
https://www.youtube.com/watch?v=CC6qvzWp9_A
Starts at around 9:25!

**Comment by dwinston** [comment]
Cool, thanks

**Comment by HGeerlings** [comment]
A brief set of install instructions has been appended to the <a href="https://github.com/mp-interns/eratosthenes/wiki/MOE-Research-and-Notes">MOE wiki page</a>

**Comment by dwinston** [comment]
I'll call this closed. We have settled on trying MOE over SigOpt for now, and everyone seems to have it installed and is exploring its use. Thank you @HGeerlings for the installation page in the wiki.
